### PR TITLE
Amendments from this year

### PR DESCRIPTION
**Pull request by HenrySwanson**
It turns out that no specific officer is responsible for updating the Constitution. As such, literally no one did that during the year of 2015-2016.

So because it's the day before SURF starts, I wrote them all up.

Also, I have no idea who has Ruddock's GitHub account. If it's still DK or Pelz, we should probably figure out who to transition it to...

### CODE REVIEW

**Comment by dkong1796** [comment]
lgtm

**Comment by dkong1796** [comment]
IMSS (plus me and Eric) are the owners of the github.

**Comment by dkong1796** [comment]
The constitution has been updated on the website.

**Comment by HenrySwanson** [comment]
Great, thanks a bunch!

**Pull request merged**
