### PR TITLE
Peer Advocate Amendment passed 11/16/17

### PR DESCRIPTION
**Pull request by ewuirl**

### CODE REVIEW

**Comment by ialexryan** [comment]
Looks legit. I'll just assume this accurately reflects what was passed

**Comment by ialexryan** [comment]
Don't forget to delete your fork! :)

**Comment by ialexryan** [comment]
Travis build completed, automatic commit to website repo worked, and I logged into `that` and pulled the website repo. New constitution is live!

**Comment by rpinkerton** [comment]
https://github.com/RuddockHouse/RuddockConstitution/pull/11/files#diff-b7f95ef634d16a50554875a0cfb523e3R230

missed one

**Pull request merged**
